// Code generated by counterfeiter. DO NOT EDIT.
package gatherfakes

import (
	"github.com/cloudfoundry-incubator/mysql-monitoring-release/src/mysql-metrics/gather"
	"sync"
)

type FakeStater struct {
	StatsStub        func(string) (uint64, uint64, uint64, uint64, error)
	statsMutex       sync.RWMutex
	statsArgsForCall []struct {
		arg1 string
	}
	statsReturns struct {
		result1 uint64
		result2 uint64
		result3 uint64
		result4 uint64
		result5 error
	}
	statsReturnsOnCall map[int]struct {
		result1 uint64
		result2 uint64
		result3 uint64
		result4 uint64
		result5 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStater) Stats(arg1 string) (uint64, uint64, uint64, uint64, error) {
	fake.statsMutex.Lock()
	ret, specificReturn := fake.statsReturnsOnCall[len(fake.statsArgsForCall)]
	fake.statsArgsForCall = append(fake.statsArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Stats", []interface{}{arg1})
	fake.statsMutex.Unlock()
	if fake.StatsStub != nil {
		return fake.StatsStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3, ret.result4, ret.result5
	}
	fakeReturns := fake.statsReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3, fakeReturns.result4, fakeReturns.result5
}

func (fake *FakeStater) StatsCallCount() int {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	return len(fake.statsArgsForCall)
}

func (fake *FakeStater) StatsCalls(stub func(string) (uint64, uint64, uint64, uint64, error)) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = stub
}

func (fake *FakeStater) StatsArgsForCall(i int) string {
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	argsForCall := fake.statsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStater) StatsReturns(result1 uint64, result2 uint64, result3 uint64, result4 uint64, result5 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	fake.statsReturns = struct {
		result1 uint64
		result2 uint64
		result3 uint64
		result4 uint64
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeStater) StatsReturnsOnCall(i int, result1 uint64, result2 uint64, result3 uint64, result4 uint64, result5 error) {
	fake.statsMutex.Lock()
	defer fake.statsMutex.Unlock()
	fake.StatsStub = nil
	if fake.statsReturnsOnCall == nil {
		fake.statsReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 uint64
			result3 uint64
			result4 uint64
			result5 error
		})
	}
	fake.statsReturnsOnCall[i] = struct {
		result1 uint64
		result2 uint64
		result3 uint64
		result4 uint64
		result5 error
	}{result1, result2, result3, result4, result5}
}

func (fake *FakeStater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.statsMutex.RLock()
	defer fake.statsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gather.Stater = new(FakeStater)
