#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$( cd ${MY_DIR}/../../.. && pwd )"
CF_MYSQL_CI_DIR="${WORKSPACE_DIR}/cf-mysql-ci"

: "${BOSH_LITE_SSH_KEY:?}"
: "${ENV_TARGET_FILE:?}"
: "${ENV_METADATA:?}"

source ${CF_MYSQL_CI_DIR}/scripts/utils.sh

BOSH_TARGET="$(cat "${ENV_TARGET_FILE}")"
ENV="$(jq_val "env" "${ENV_METADATA}")"
BOSH_USER="$(jq_val "bosh_user" "${ENV_METADATA}")"
BOSH_PASSWORD="$(jq_val "bosh_password" "${ENV_METADATA}")"

MYSQL_TUNNEL_IP=127.0.0.1
MYSQL_TUNNEL_PORT=3307
MYSQL_TUNNEL_USERNAME=ubuntu
MYSQL_VM_IP=10.244.7.2
MYSQL_VM_PORT=3306

function close-ssh-tunnels() {
  echo "Closing SSH tunnels ..."
  OLD_TUNNELS=`ps aux | grep "ssh" | grep "\-L $MYSQL_TUNNEL_PORT" | awk '{print $2}'`
  [[ -z "${OLD_TUNNELS}" ]] || kill ${OLD_TUNNELS}
}

function open_ssh_tunnel_to_bosh_lite() {
  SSH_KEY_FILE="bosh-lite-key"
  echo "${BOSH_LITE_SSH_KEY}" > "${SSH_KEY_FILE}"
  chmod 600 "${SSH_KEY_FILE}"

  ssh -L ${MYSQL_TUNNEL_PORT}:${MYSQL_VM_IP}:${MYSQL_VM_PORT} \
    -nNTf \
    -o StrictHostKeyChecking=no \
    -i "${SSH_KEY_FILE}" \
    ${MYSQL_TUNNEL_USERNAME}@${BOSH_TARGET}
}

function create_notifications_db() {
  MYSQL_HOST=${MYSQL_TUNNEL_IP}
  MYSQL_PORT=${MYSQL_TUNNEL_PORT}

  NOTIFICATIONS_DB=notifications_db

  mysql --host=${MYSQL_HOST} \
    --port=${MYSQL_PORT} \
    --user=root \
    --password=password \
    -e "CREATE DATABASE IF NOT EXISTS ${NOTIFICATIONS_DB}"
}

function main() {
  trap close-ssh-tunnels EXIT

  open_ssh_tunnel_to_bosh_lite
  create_notifications_db
}
