#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKSPACE_DIR="$(cd "${MY_DIR}/../../.." && pwd)"
RELEASE_DIR="${WORKSPACE_DIR}/${RELEASE_REPO_DIR:-mysql-monitoring-release}"
GIT_KEY_FILE="${WORKSPACE_DIR}/git-private-key"
OUTPUT_DIR="${WORKSPACE_DIR}/${OUTPUT_DIR:-output-release-dir}"

function write_upload_keys() {
  pushd ${WORKSPACE_DIR}
    echo -e "${GITHUB_KEY}" > ${GIT_KEY_FILE}
  popd
  eval $(ssh-agent)
  chmod 0600 ${GIT_KEY_FILE}
  ssh-add ${GIT_KEY_FILE}
}

function create_release() {
  pushd "${RELEASE_DIR}"
    git pull -r
    VERSION=$(git describe --long --tags)
    RC_VERSION=$(echo ${VERSION} | sed -E 's/^v([^-]*)(.*)/\1-rc\2/')
    bosh -n create release --with-tarball --version ${RC_VERSION}
  popd
}

write_upload_keys
create_release

cp -r "${RELEASE_DIR}"/dev_releases/mysql-monitoring/mysql-monitoring-*.tgz "${OUTPUT_DIR}/"
