#!/bin/bash

set -eu

job_dir=/var/vcap/jobs/replication-canary
package_dir=/var/vcap/packages/replication-canary
config_path="${job_dir}/config/replication-canary.yml"

executable_name=writer
executable="${package_dir}/bin/${executable_name}"

$executable \
  -configPath="${config_path}"
