// Code generated by counterfeiter. DO NOT EDIT.
package alertfakes

import (
	"sync"

	"github.com/cloudfoundry/replication-canary/alert"
)

type FakeAlerter struct {
	NotUnhealthyStub        func() error
	notUnhealthyMutex       sync.RWMutex
	notUnhealthyArgsForCall []struct {
	}
	notUnhealthyReturns struct {
		result1 error
	}
	notUnhealthyReturnsOnCall map[int]struct {
		result1 error
	}
	UnhealthyStub        func() error
	unhealthyMutex       sync.RWMutex
	unhealthyArgsForCall []struct {
	}
	unhealthyReturns struct {
		result1 error
	}
	unhealthyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAlerter) NotUnhealthy() error {
	fake.notUnhealthyMutex.Lock()
	ret, specificReturn := fake.notUnhealthyReturnsOnCall[len(fake.notUnhealthyArgsForCall)]
	fake.notUnhealthyArgsForCall = append(fake.notUnhealthyArgsForCall, struct {
	}{})
	stub := fake.NotUnhealthyStub
	fakeReturns := fake.notUnhealthyReturns
	fake.recordInvocation("NotUnhealthy", []interface{}{})
	fake.notUnhealthyMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAlerter) NotUnhealthyCallCount() int {
	fake.notUnhealthyMutex.RLock()
	defer fake.notUnhealthyMutex.RUnlock()
	return len(fake.notUnhealthyArgsForCall)
}

func (fake *FakeAlerter) NotUnhealthyCalls(stub func() error) {
	fake.notUnhealthyMutex.Lock()
	defer fake.notUnhealthyMutex.Unlock()
	fake.NotUnhealthyStub = stub
}

func (fake *FakeAlerter) NotUnhealthyReturns(result1 error) {
	fake.notUnhealthyMutex.Lock()
	defer fake.notUnhealthyMutex.Unlock()
	fake.NotUnhealthyStub = nil
	fake.notUnhealthyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAlerter) NotUnhealthyReturnsOnCall(i int, result1 error) {
	fake.notUnhealthyMutex.Lock()
	defer fake.notUnhealthyMutex.Unlock()
	fake.NotUnhealthyStub = nil
	if fake.notUnhealthyReturnsOnCall == nil {
		fake.notUnhealthyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.notUnhealthyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAlerter) Unhealthy() error {
	fake.unhealthyMutex.Lock()
	ret, specificReturn := fake.unhealthyReturnsOnCall[len(fake.unhealthyArgsForCall)]
	fake.unhealthyArgsForCall = append(fake.unhealthyArgsForCall, struct {
	}{})
	stub := fake.UnhealthyStub
	fakeReturns := fake.unhealthyReturns
	fake.recordInvocation("Unhealthy", []interface{}{})
	fake.unhealthyMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAlerter) UnhealthyCallCount() int {
	fake.unhealthyMutex.RLock()
	defer fake.unhealthyMutex.RUnlock()
	return len(fake.unhealthyArgsForCall)
}

func (fake *FakeAlerter) UnhealthyCalls(stub func() error) {
	fake.unhealthyMutex.Lock()
	defer fake.unhealthyMutex.Unlock()
	fake.UnhealthyStub = stub
}

func (fake *FakeAlerter) UnhealthyReturns(result1 error) {
	fake.unhealthyMutex.Lock()
	defer fake.unhealthyMutex.Unlock()
	fake.UnhealthyStub = nil
	fake.unhealthyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAlerter) UnhealthyReturnsOnCall(i int, result1 error) {
	fake.unhealthyMutex.Lock()
	defer fake.unhealthyMutex.Unlock()
	fake.UnhealthyStub = nil
	if fake.unhealthyReturnsOnCall == nil {
		fake.unhealthyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unhealthyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAlerter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.notUnhealthyMutex.RLock()
	defer fake.notUnhealthyMutex.RUnlock()
	fake.unhealthyMutex.RLock()
	defer fake.unhealthyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAlerter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ alert.Alerter = new(FakeAlerter)
