#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

topdir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "${topdir}" || exit 1

director_name=$(bosh curl /info | jq -r .name)

bosh --non-interactive --deployment=pxc deploy \
  ../pxc-release/pxc-deployment.yml \
  -o ../pxc-release/operations/use-clustered.yml \
  -o ../pxc-release/operations/minimal-mode.yml \
  -o ../pxc-release/operations/register-proxy-route.yml \
  -o ../dedicated-mysql-ci/ops-files/pxc/proxy-route-registrar-uses-nats-tls.yml \
  -o ../dedicated-mysql-ci/ops-files/monitoring/pxc-add-notifications-db.yml \
  -o ../pxc-release/operations/experimental/fast-deploy-with-downtime-and-danger.yml \
  -o operations/pxc-add-metrics.yml \
  -o operations/pxc-add-monitoring.yml \
  -o operations/mysql-diag-agent-tls.yml \
  -o operations/replication-canary-tls.yml \
  -o operations/dev-release.yml \
  -v proxy_route_suffix="proxy.${SYSTEM_DOMAIN}" \
  -v cf_skip_ssl_validation=true \
  -v mysql_monitoring_recipient_email=test@example.com \
  -v mysql_monitoring_cluster_identifier=pxc \
  -v mysql_monitoring_replication_canary_uaa_admin_client_secret="((/${director_name}/cf/uaa_admin_client_secret))" \
  -v bosh_director_name="${director_name}"

