#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

topdir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "${topdir}" || exit 1

run() {
  echo "\$ $*"
  "$@"
}

director_name=$(bosh curl /info | jq -r .name)

# Override these environment variables if cf or bosh is deployed differently
# Defaults to cf-deployment and related OSS cloud-config values
: "${BOSH_DEPLOYMENT=pxc}"
: "${MYSQL_VERSION:=}"
: "${cf_deployment_name:=cf}"
: "${BOSH_VAR_azs:='[z1,z2,z3]'}"
: "${BOSH_VAR_network:=default}"
: "${BOSH_VAR_vm_type:=default}"
: "${BOSH_VAR_source_id:=pxc-metrics-test}"
: "${BOSH_VAR_loggregator_tls_ca:=((/$director_name/${cf_deployment_name}/loggregator_tls_agent.ca))}"
: "${BOSH_VAR_loggregator_tls_client_cert:=((/$director_name/${cf_deployment_name}/loggregator_tls_agent.certificate))}"
: "${BOSH_VAR_loggregator_tls_client_key:=((/$director_name/${cf_deployment_name}/loggregator_tls_agent.private_key))}"

export BOSH_DEPLOYMENT
export BOSH_VAR_azs BOSH_VAR_network BOSH_VAR_vm_type
export BOSH_VAR_source_id
export BOSH_VAR_loggregator_tls_ca BOSH_VAR_loggregator_tls_client_cert BOSH_VAR_loggregator_tls_client_key

deploy_opts=(
  --vars-env=BOSH_VAR
  --var="deployment_name=$BOSH_DEPLOYMENT"
)

if [[ -n ${MYSQL_VERSION} ]]; then
  export BOSH_VAR_mysql_version="'${MYSQL_VERSION}'"

  deploy_opts+=(--ops-file=operations/pxc-set-mysql-version.yml)
fi

deploy_opts+=("$@")

run bosh deploy manifest/pxc.yml \
  --no-redact \
  --non-interactive \
  "${deploy_opts[@]}"
