#!/bin/bash

set -o errexit -o nounset -o pipefail

RELEASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "${RELEASE_DIR}"
bundle install
bundle exec rspec ./spec

echo -e "\nTesting Release-Level Specs..."
"${RELEASE_DIR}"/src/spec/bin/test "$@"

echo -e "\nTesting Metrics..."
"${RELEASE_DIR}"/src/mysql-metrics/bin/test "$@"

echo -e "\nTesting Replication Canary..."
"${RELEASE_DIR}"/src/replication-canary/bin/test "$@"

echo -e "\nTesting Mysql-Diag..."
"${RELEASE_DIR}"/src/mysql-diag/bin/test "$@"

echo -e "\nTesting Notifications Client..."
"${RELEASE_DIR}"/src/replication-canary/notifications-client/bin/test "$@"
