#!/bin/bash

set -euxo pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd $MY_DIR/.. && pwd )"

source ${RELEASE_DIR}/.envrc

gem install bosh-template

echo -e "\nTesting Release-Level Specs..."
${RELEASE_DIR}/src/spec/bin/test "$@"

echo -e "\nTesting Metrics..."
${RELEASE_DIR}/src/mysql-metrics/bin/test "$@"

echo -e "\nTesting Replication Canary..."
${RELEASE_DIR}/src/replication-canary/bin/test "$@"

echo -e "\nTesting Mysql-Diag..."
${RELEASE_DIR}/src/mysql-diag/bin/test "$@"

echo -e "\nTesting Notifications Client..."
${RELEASE_DIR}/src/replication-canary/notifications-client/bin/test "$@"
