#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd $MY_DIR/.. && pwd )"

source ${RELEASE_DIR}/.envrc

echo -e "\nTesting Replication Canary..."
${RELEASE_DIR}/src/replication-canary/bin/test-integration "$@"

