// Code generated by counterfeiter. DO NOT EDIT.
package metricsfakes

import (
	"sync"

	"github.com/cloudfoundry/mysql-metrics/metrics"
)

type FakeSender struct {
	SendBatchStub        func([]metrics.MetricDatum) error
	sendBatchMutex       sync.RWMutex
	sendBatchArgsForCall []struct {
		arg1 []metrics.MetricDatum
	}
	sendBatchReturns struct {
		result1 error
	}
	sendBatchReturnsOnCall map[int]struct {
		result1 error
	}
	SendValueStub        func(string, float64, string) error
	sendValueMutex       sync.RWMutex
	sendValueArgsForCall []struct {
		arg1 string
		arg2 float64
		arg3 string
	}
	sendValueReturns struct {
		result1 error
	}
	sendValueReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSender) SendBatch(arg1 []metrics.MetricDatum) error {
	var arg1Copy []metrics.MetricDatum
	if arg1 != nil {
		arg1Copy = make([]metrics.MetricDatum, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.sendBatchMutex.Lock()
	ret, specificReturn := fake.sendBatchReturnsOnCall[len(fake.sendBatchArgsForCall)]
	fake.sendBatchArgsForCall = append(fake.sendBatchArgsForCall, struct {
		arg1 []metrics.MetricDatum
	}{arg1Copy})
	stub := fake.SendBatchStub
	fakeReturns := fake.sendBatchReturns
	fake.recordInvocation("SendBatch", []interface{}{arg1Copy})
	fake.sendBatchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSender) SendBatchCallCount() int {
	fake.sendBatchMutex.RLock()
	defer fake.sendBatchMutex.RUnlock()
	return len(fake.sendBatchArgsForCall)
}

func (fake *FakeSender) SendBatchCalls(stub func([]metrics.MetricDatum) error) {
	fake.sendBatchMutex.Lock()
	defer fake.sendBatchMutex.Unlock()
	fake.SendBatchStub = stub
}

func (fake *FakeSender) SendBatchArgsForCall(i int) []metrics.MetricDatum {
	fake.sendBatchMutex.RLock()
	defer fake.sendBatchMutex.RUnlock()
	argsForCall := fake.sendBatchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSender) SendBatchReturns(result1 error) {
	fake.sendBatchMutex.Lock()
	defer fake.sendBatchMutex.Unlock()
	fake.SendBatchStub = nil
	fake.sendBatchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) SendBatchReturnsOnCall(i int, result1 error) {
	fake.sendBatchMutex.Lock()
	defer fake.sendBatchMutex.Unlock()
	fake.SendBatchStub = nil
	if fake.sendBatchReturnsOnCall == nil {
		fake.sendBatchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendBatchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) SendValue(arg1 string, arg2 float64, arg3 string) error {
	fake.sendValueMutex.Lock()
	ret, specificReturn := fake.sendValueReturnsOnCall[len(fake.sendValueArgsForCall)]
	fake.sendValueArgsForCall = append(fake.sendValueArgsForCall, struct {
		arg1 string
		arg2 float64
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.SendValueStub
	fakeReturns := fake.sendValueReturns
	fake.recordInvocation("SendValue", []interface{}{arg1, arg2, arg3})
	fake.sendValueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSender) SendValueCallCount() int {
	fake.sendValueMutex.RLock()
	defer fake.sendValueMutex.RUnlock()
	return len(fake.sendValueArgsForCall)
}

func (fake *FakeSender) SendValueCalls(stub func(string, float64, string) error) {
	fake.sendValueMutex.Lock()
	defer fake.sendValueMutex.Unlock()
	fake.SendValueStub = stub
}

func (fake *FakeSender) SendValueArgsForCall(i int) (string, float64, string) {
	fake.sendValueMutex.RLock()
	defer fake.sendValueMutex.RUnlock()
	argsForCall := fake.sendValueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSender) SendValueReturns(result1 error) {
	fake.sendValueMutex.Lock()
	defer fake.sendValueMutex.Unlock()
	fake.SendValueStub = nil
	fake.sendValueReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) SendValueReturnsOnCall(i int, result1 error) {
	fake.sendValueMutex.Lock()
	defer fake.sendValueMutex.Unlock()
	fake.SendValueStub = nil
	if fake.sendValueReturnsOnCall == nil {
		fake.sendValueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendValueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Sender = new(FakeSender)
